UI/Controllers/StudentInfoController.cs
using BLL;
using Model;
using Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Controllers
{
    public class StudentInfoController : Controller
    {
        StudentInfoBLL sbll = new StudentInfoBLL();
        ClassInfoBLL cbll = new ClassInfoBLL();
        // GET: StudetInfo
        public ActionResult Index()
        {
            //ViewData.Model = sbll.GetAll(5,1);
            return View();
        }
        public ActionResult LoadPageList(int pageSize,int pageIndex)
        {
            int elems = sbll.GetAll().Count();
            int pageCount =Convert.ToInt32( Math.Ceiling(elems*1.0/ pageSize));
            pageIndex = pageIndex < 1 ? 1 : pageIndex;
            pageIndex = pageIndex > pageCount ? pageCount : pageIndex;           
            var list = sbll.GetPageList(pageSize,pageIndex)
                .Select(x => new
                {
                    Id = x.sId,
                    Name = x.sName,
                    Gender = x.sGender,
                    DOB = x.sBirthday,
                    Phone = x.sPhone,
                    Email = x.sEMail,
                    Class = x.ClassInfo.cTitle
                })
                .ToList();
            string pgbar = PageBar.GetPageBar(pageIndex, pageCount);
            return Json(new { myList = list, myPageBar = pgbar }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Add()
        {
            List<SelectListItem> list = new List<SelectListItem>();
            var l = cbll.GetAll();
            foreach (var item in l)
            {
                list.Add(new SelectListItem() {
                    Text = item.cTitle,
                    Value = item.cId.ToString()
                });
            }
            ViewBag.ClassList = list;
            
            return View();
        }
        [HttpPost]
        public ActionResult Add(StudentInfo s)
        {
            sbll.Add(s);
            return Redirect(Url.Action("Index"));
        }
    }
}

UI/Views/StudentInfo/Add.cshtml
@model Model.StudentInfo
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add</title>
    <link href="~/CSS/jquery-ui.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery-ui.js"></script>
    <script type="text/javascript">
       $(function () {
            $("#birth_date").datepicker();
        });
    </script>
</head>
<body>
    <div> 
        @using (Html.BeginForm("Add","StudentInfo",FormMethod.Post))
        {
            
            <span>Name:</span> @Html.TextBoxFor(s=>s.sName)<br />
            
            <span>Gender:</span> @Html.RadioButtonFor(s => s.sGender, false)
            <label for="female">Female</label>
            @Html.RadioButtonFor(s => s.sGender, true)
            <label for="male">Male</label><br />
            <span>DOB:</span> @Html.TextBoxFor(s => s.sBirthday,new { id = "birth_date" })
            <br /> 
            <span>Phone:</span>@Html.TextBoxFor(s => s.sPhone)<br />
            <span>Email:</span>@Html.TextBoxFor(s => s.sEMail)<br />
            <span>Class:</span>@Html.DropDownListFor(s => s.cid, (IEnumerable<SelectListItem>)ViewBag.ClassList, "--Select Class--")<br />
            
            <input type="submit" value="Add" />
        }
    </div>
</body>
</html>

UI/Views/StudentInfo/Index.cshtml
@model IQueryable<Model.StudentInfo>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>   
    <link href="~/CSS/PageBar.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script type="text/javascript">      
        $(function() {
            LoadList(1);
        });
        function LoadList(pageIndex) {
            //Ajax
            $.getJSON('@Url.Action("LoadPageList", "StudentInfo")', { pageSize: 5, pageIndex: pageIndex }, function (data) {
                var list = $('#list');
                list.empty();
                $.each(data.myList, function(index,value) {
                    list.append('<tr><td>' + value.Id + '</td><td>' + value.Name + '</td><td>' + value.Gender + '</td><td>' + ChangeDateFormat(value.DOB) + '</td><td>' + value.Phone + '</td><td>' + value.Email + '</td><td>' + value.Class + '</td></tr>');
                });
                $('#showPageBar ul').html(data.myPageBar);
                bindPageBarClickEvent();
            });
        }

        function bindPageBarClickEvent() {
            $(".pgbar").click(function () {
                var pageIndex = $(this).attr("href").split('=')[1];
                //$("#tabList tr:gt(0)").remove();
                //$('#list').empty();
                LoadList(pageIndex);
                return false;
            });
        }
        function ChangeDateFormat(cellval) {
            var date = new Date(parseInt(cellval.replace("/Date(", "").replace(")/", ""), 10));
            //getMonth()从0开始算
            var month = date.getMonth() + 1 < 10 ? "0" + (date.getMonth() + 1) : date.getMonth() + 1;
            var currentDate = date.getDate() < 10 ? "0" + date.getDate() : date.getDate();
            return date.getFullYear() + "-" + month + "-" + currentDate;
        }
    </script>
</head>
<body>
    <div> 
        @Html.ActionLink("Add New", "Add", "StudentInfo")
        <table border="1" id="tabList">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Gender</th>
                <th>DOB</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Class</th>
            </tr>
            <tbody id="list">

            </tbody>
              
            @*@foreach (var s in Model)
            {
                <tr>
                    <td>@s.sId</td>
                    <td>@s.sName</td>
                    <td>@s.sGender</td>
                    <td>@s.sBirthday.ToShortDateString()</td>
                    <td>@s.sPhone</td>
                    <td>@s.sEMail</td>
                    <td>@s.ClassInfo.cTitle</td>
                </tr>
            }*@
        </table>
        <div id="showPageBar" class="center">
            <ul class="pagination"></ul>
        </div> 
    </div>
</body>
</html>