UI/Controllers/ClassInfoController.cs
using BLL;
using Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Controllers
{//CRUD
    public class ClassInfoController : Controller
    {
        ClassInfoBLL bll = new ClassInfoBLL();
        // GET: ClassInfo
        public ActionResult Index()
        {
            ViewData.Model= bll.GetAll();
            return View();
        }
        //CREATE
        public ActionResult Add()
        {
            return View();
        }
        //ADD POST
        [HttpPost]
        public ActionResult Add(ClassInfo c)
        {
            bll.Add(c);
            return Redirect(Url.Action("Index"));
        }
        //UPDATE 
        public ActionResult Edit(int id)
        {          
            ClassInfo EditContent = bll.GetById(id);                     
            return View(EditContent);
        }
        [HttpPost]
        public ActionResult Edit(ClassInfo c)
        {
            bll.Edit(c);
            return Redirect(Url.Action("Index"));
        }
        //DELETE
        public ActionResult Delete(int id)
        {
            bll.Delete(id);
            return Redirect(Url.Action("Index"));
        }
    }
}

UI/Views/ClassInfo/Add.cshtml
@model Model.ClassInfo
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add</title>
</head>
<body>
    <div> 
        @using (Html.BeginForm("Add","ClassInfo",FormMethod.Post))
        {
            @Html.TextBoxFor(c=>c.cTitle)
            <input type="submit"  value="Add" />
        }
        
    </div>
</body>
</html>

UI/Views/ClassInfo/Edit.cshtml
@model Model.ClassInfo
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    <div> 
        @using (Html.BeginForm("Edit", "ClassInfo", FormMethod.Post))
        {
            <label>Class Name:</label>@Html.TextBoxFor(c => c.cTitle)<br />
            @Html.HiddenFor(c => c.cId)
            <input type="submit" value="Edit" />
        }
    </div>
</body>
</html>

UI/Views/ClassInfo/Index.cshtml
@model IQueryable<Model.ClassInfo> 
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        @Html.ActionLink("Add New","Add","ClassInfo")
        <table border="0">
            <tr>
                <th>ID</th><th>Title</th>
            </tr>
            @foreach (var c in Model)
            {
                <tr>
                    <td>@c.cId</td>
                    <td>@c.cTitle</td>
                    <td>@Html.ActionLink("Edit", "Edit", "ClassInfo",new {id=c.cId},null)</td>
                    <td>@Html.ActionLink("Delete", "Delete", "ClassInfo", new { id = c.cId }, null)</td>
                </tr>
            }
        </table>
    </div>
</body>
</html>